// Code generated by qtc from "articles.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line articles.qtpl:1
package templates

//line articles.qtpl:1
import "tochkru-golang/internal/app/datastruct"

//line articles.qtpl:2
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line articles.qtpl:2
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line articles.qtpl:2
func StreamArticlesPage(qw422016 *qt422016.Writer, articles []datastruct.Articles, tags map[int]datastruct.Tags, teamMembers map[int]datastruct.TeamMembers, topTags []datastruct.Tags) {
//line articles.qtpl:2
	qw422016.N().S(`
`)
//line articles.qtpl:3
	qw422016.N().S(Header("Статьи"))
//line articles.qtpl:3
	qw422016.N().S(`
`)
//line articles.qtpl:4
	qw422016.N().S(Menu(topTags))
//line articles.qtpl:4
	qw422016.N().S(`
`)
//line articles.qtpl:5
	for i := 0; i < len(articles); i++ {
//line articles.qtpl:5
		qw422016.N().S(`
`)
//line articles.qtpl:6
		qw422016.N().S(Article(articles[i], tags, teamMembers))
//line articles.qtpl:6
		qw422016.N().S(`
`)
//line articles.qtpl:7
	}
//line articles.qtpl:7
	qw422016.N().S(`
`)
//line articles.qtpl:8
	qw422016.N().S(Footer())
//line articles.qtpl:8
	qw422016.N().S(`
`)
//line articles.qtpl:9
}

//line articles.qtpl:9
func WriteArticlesPage(qq422016 qtio422016.Writer, articles []datastruct.Articles, tags map[int]datastruct.Tags, teamMembers map[int]datastruct.TeamMembers, topTags []datastruct.Tags) {
//line articles.qtpl:9
	qw422016 := qt422016.AcquireWriter(qq422016)
//line articles.qtpl:9
	StreamArticlesPage(qw422016, articles, tags, teamMembers, topTags)
//line articles.qtpl:9
	qt422016.ReleaseWriter(qw422016)
//line articles.qtpl:9
}

//line articles.qtpl:9
func ArticlesPage(articles []datastruct.Articles, tags map[int]datastruct.Tags, teamMembers map[int]datastruct.TeamMembers, topTags []datastruct.Tags) string {
//line articles.qtpl:9
	qb422016 := qt422016.AcquireByteBuffer()
//line articles.qtpl:9
	WriteArticlesPage(qb422016, articles, tags, teamMembers, topTags)
//line articles.qtpl:9
	qs422016 := string(qb422016.B)
//line articles.qtpl:9
	qt422016.ReleaseByteBuffer(qb422016)
//line articles.qtpl:9
	return qs422016
//line articles.qtpl:9
}
