// Code generated by qtc from "main.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line main.qtpl:1
package templates

//line main.qtpl:1
import "tochkru-golang/internal/app/datastruct"

//line main.qtpl:3
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line main.qtpl:3
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line main.qtpl:3
func StreamHeader(qw422016 *qt422016.Writer, title string) {
//line main.qtpl:3
	qw422016.N().S(`
<!DOCTYPE html>
<html>
<head>
    <title>`)
//line main.qtpl:7
	qw422016.E().S(title)
//line main.qtpl:7
	qw422016.N().S(`</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <link href="/static/style.css" rel="stylesheet" type="text/css"/>
    <link href="/favicon.ico" rel="shortcut icon" type="image/x-icon"/>
    <link href='https://fonts.googleapis.com/css?family=Roboto+Slab&subset=latin,cyrillic' rel='stylesheet'
          type='text/css'>
</head>
<body>
`)
//line main.qtpl:15
}

//line main.qtpl:15
func WriteHeader(qq422016 qtio422016.Writer, title string) {
//line main.qtpl:15
	qw422016 := qt422016.AcquireWriter(qq422016)
//line main.qtpl:15
	StreamHeader(qw422016, title)
//line main.qtpl:15
	qt422016.ReleaseWriter(qw422016)
//line main.qtpl:15
}

//line main.qtpl:15
func Header(title string) string {
//line main.qtpl:15
	qb422016 := qt422016.AcquireByteBuffer()
//line main.qtpl:15
	WriteHeader(qb422016, title)
//line main.qtpl:15
	qs422016 := string(qb422016.B)
//line main.qtpl:15
	qt422016.ReleaseByteBuffer(qb422016)
//line main.qtpl:15
	return qs422016
//line main.qtpl:15
}

//line main.qtpl:17
func StreamMenu(qw422016 *qt422016.Writer, isAdmin bool) {
//line main.qtpl:17
	qw422016.N().S(`
<header>
    <div id="header_for_buttons">
        <div id="logo_name" onclick="window.location.href='/'"><h1>TOCHK.RU</h1></div>
        <div id="buttons">
            `)
//line main.qtpl:22
	if isAdmin {
//line main.qtpl:22
		qw422016.N().S(` <div id="button" onclick="window.location.href='/admin/'">АДМИНКА</div> `)
//line main.qtpl:22
	}
//line main.qtpl:22
	qw422016.N().S(`
            <div id="button" onclick="window.location.href='/projects/'">ПРОЕКТЫ</div>
            <div id="button" onclick="window.location.href='/blog/'">СТАТЬИ</div>
            <div id="button" onclick="window.location.href='/'">ГЛАВНАЯ</div>
        </div>
    </div>
</header>
<main>
    <div id="top_menu">
        <div id="header_top"></div>
    </div>
    <div id="left_menu">
        <div id="block_for_left">
            <div id="head_left_menu">TAGS</div>
            <div id="info_left_menu">TODO</div>
        </div>
    </div>
    <div id="right_menu">
        <content>
`)
//line main.qtpl:41
}

//line main.qtpl:41
func WriteMenu(qq422016 qtio422016.Writer, isAdmin bool) {
//line main.qtpl:41
	qw422016 := qt422016.AcquireWriter(qq422016)
//line main.qtpl:41
	StreamMenu(qw422016, isAdmin)
//line main.qtpl:41
	qt422016.ReleaseWriter(qw422016)
//line main.qtpl:41
}

//line main.qtpl:41
func Menu(isAdmin bool) string {
//line main.qtpl:41
	qb422016 := qt422016.AcquireByteBuffer()
//line main.qtpl:41
	WriteMenu(qb422016, isAdmin)
//line main.qtpl:41
	qs422016 := string(qb422016.B)
//line main.qtpl:41
	qt422016.ReleaseByteBuffer(qb422016)
//line main.qtpl:41
	return qs422016
//line main.qtpl:41
}

//line main.qtpl:44
func StreamFooter(qw422016 *qt422016.Writer, year int) {
//line main.qtpl:44
	qw422016.N().S(`
        </content>
    </div>
</main>
<footer>
    design by lenokh // tochk.ru 2015 - `)
//line main.qtpl:49
	qw422016.N().D(year)
//line main.qtpl:49
	qw422016.N().S(`
</footer>
</body>
</html>
`)
//line main.qtpl:53
}

//line main.qtpl:53
func WriteFooter(qq422016 qtio422016.Writer, year int) {
//line main.qtpl:53
	qw422016 := qt422016.AcquireWriter(qq422016)
//line main.qtpl:53
	StreamFooter(qw422016, year)
//line main.qtpl:53
	qt422016.ReleaseWriter(qw422016)
//line main.qtpl:53
}

//line main.qtpl:53
func Footer(year int) string {
//line main.qtpl:53
	qb422016 := qt422016.AcquireByteBuffer()
//line main.qtpl:53
	WriteFooter(qb422016, year)
//line main.qtpl:53
	qs422016 := string(qb422016.B)
//line main.qtpl:53
	qt422016.ReleaseByteBuffer(qb422016)
//line main.qtpl:53
	return qs422016
//line main.qtpl:53
}

//line main.qtpl:56
func StreamProject(qw422016 *qt422016.Writer, project datastruct.Projects) {
//line main.qtpl:56
	qw422016.N().S(`
<div id='block_new_sait' onclick="window.open('/project/`)
//line main.qtpl:57
	qw422016.N().D(project.ID)
//line main.qtpl:57
	qw422016.N().S(`', '_blank');">
    <div id='block_in_block_sait'>
    <div id='block_in_block_sait_2'>
    <div id='block_sait_head'>`)
//line main.qtpl:60
	qw422016.E().S(project.Title)
//line main.qtpl:60
	qw422016.N().S(`</div>
    <div id='block_sait_scrin_info'>
    <div class='block_sait_scrin_1'>
    <div class='block_sait_scrin_2' style='background-image: url("`)
//line main.qtpl:63
	qw422016.N().S(project.ImageURL)
//line main.qtpl:63
	qw422016.N().S(`")'></div>
    <div class='block_sait_scrin_3'>`)
//line main.qtpl:64
	qw422016.N().S(project.ShortDescription)
//line main.qtpl:64
	qw422016.N().S(`</div>
    </div></div></div></div><div id='block_sait_info'>
    <div id='block_sait_info_2'>
    <div id='sait_date' style='width: 100px'>`)
//line main.qtpl:67
	qw422016.E().V(project.CreatedAt)
//line main.qtpl:67
	qw422016.N().S(`</div>
    <div id='sait_data_about_block' style='width: 180px'>
    <div style='width: 80px' id='sait_author'>Team<br><text_green>{$row['author']}</text_green></div>
    <div style='width: 80px' id='sait_cat'>Category<br><text_green>{$row['category']}</text_green></div>
    </div><div id='sait_right_footer'>read more</div>
</div></div></div>
`)
//line main.qtpl:73
}

//line main.qtpl:73
func WriteProject(qq422016 qtio422016.Writer, project datastruct.Projects) {
//line main.qtpl:73
	qw422016 := qt422016.AcquireWriter(qq422016)
//line main.qtpl:73
	StreamProject(qw422016, project)
//line main.qtpl:73
	qt422016.ReleaseWriter(qw422016)
//line main.qtpl:73
}

//line main.qtpl:73
func Project(project datastruct.Projects) string {
//line main.qtpl:73
	qb422016 := qt422016.AcquireByteBuffer()
//line main.qtpl:73
	WriteProject(qb422016, project)
//line main.qtpl:73
	qs422016 := string(qb422016.B)
//line main.qtpl:73
	qt422016.ReleaseByteBuffer(qb422016)
//line main.qtpl:73
	return qs422016
//line main.qtpl:73
}
