// Code generated by qtc from "project.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line project.qtpl:1
package templates

//line project.qtpl:1
import "tochkru-golang/internal/app/datastruct"

//line project.qtpl:2
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line project.qtpl:2
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line project.qtpl:2
func StreamProjectPage(qw422016 *qt422016.Writer, project datastruct.Projects, tags map[int]datastruct.Tags, teamMembers map[int]datastruct.TeamMembers, topTags []datastruct.Tags) {
//line project.qtpl:2
	qw422016.N().S(`
`)
//line project.qtpl:3
	qw422016.N().S(Header(project.Title))
//line project.qtpl:3
	qw422016.N().S(`
`)
//line project.qtpl:4
	qw422016.N().S(Menu(topTags))
//line project.qtpl:4
	qw422016.N().S(`
`)
//line project.qtpl:5
	qw422016.N().S(FullProject(project, tags, teamMembers))
//line project.qtpl:5
	qw422016.N().S(`
`)
//line project.qtpl:6
	qw422016.N().S(Footer())
//line project.qtpl:6
	qw422016.N().S(`
`)
//line project.qtpl:7
}

//line project.qtpl:7
func WriteProjectPage(qq422016 qtio422016.Writer, project datastruct.Projects, tags map[int]datastruct.Tags, teamMembers map[int]datastruct.TeamMembers, topTags []datastruct.Tags) {
//line project.qtpl:7
	qw422016 := qt422016.AcquireWriter(qq422016)
//line project.qtpl:7
	StreamProjectPage(qw422016, project, tags, teamMembers, topTags)
//line project.qtpl:7
	qt422016.ReleaseWriter(qw422016)
//line project.qtpl:7
}

//line project.qtpl:7
func ProjectPage(project datastruct.Projects, tags map[int]datastruct.Tags, teamMembers map[int]datastruct.TeamMembers, topTags []datastruct.Tags) string {
//line project.qtpl:7
	qb422016 := qt422016.AcquireByteBuffer()
//line project.qtpl:7
	WriteProjectPage(qb422016, project, tags, teamMembers, topTags)
//line project.qtpl:7
	qs422016 := string(qb422016.B)
//line project.qtpl:7
	qt422016.ReleaseByteBuffer(qb422016)
//line project.qtpl:7
	return qs422016
//line project.qtpl:7
}

//line project.qtpl:9
func StreamFullProject(qw422016 *qt422016.Writer, project datastruct.Projects, tags map[int]datastruct.Tags, teamMembers map[int]datastruct.TeamMembers) {
//line project.qtpl:9
	qw422016.N().S(`
<article id='block_news'>
    <div id='block_in_block_news'>
    <div id='block_in_block_news_2'>
    <div id='block_news_head' style='font-size:20px;'><a href='/project/`)
//line project.qtpl:13
	qw422016.N().D(project.ID)
//line project.qtpl:13
	qw422016.N().S(`'><h1 style="font-size: 20px">`)
//line project.qtpl:13
	qw422016.E().S(project.Title)
//line project.qtpl:13
	qw422016.N().S(`</h1></a></div>
    <div id='block_news_content' style='font-size:16px;'>
        <a href="`)
//line project.qtpl:15
	qw422016.N().S(project.RedirectURL)
//line project.qtpl:15
	qw422016.N().S(`" target="_blank">Project link</a><br><br>
        `)
//line project.qtpl:16
	qw422016.N().S(project.Description)
//line project.qtpl:16
	qw422016.N().S(`
    </div>
    </div></div>
    <div id='block_news_info'>
    <div id='block_news_info_2'>
    <div id='block_date' style='font-size: 20px;'>`)
//line project.qtpl:21
	qw422016.E().S(project.CreatedAt.Format("2006.01.02"))
//line project.qtpl:21
	qw422016.N().S(`</div>
    <div id='block_data'>
    <author id='data_author'> Author<br><text_green>`)
//line project.qtpl:23
	for _, teamMemberID := range project.TeamMembersIDs {
//line project.qtpl:23
		qw422016.E().S(teamMembers[teamMemberID].Name)
//line project.qtpl:23
		qw422016.N().S(`<br>`)
//line project.qtpl:23
	}
//line project.qtpl:23
	qw422016.N().S(`<br></text_green></author>
    <div id='data_category'> Tags<br><text_green>`)
//line project.qtpl:24
	for _, tagID := range project.TagsIDs {
//line project.qtpl:24
		qw422016.E().S(tags[tagID].Name)
//line project.qtpl:24
		qw422016.N().S(`<br>`)
//line project.qtpl:24
	}
//line project.qtpl:24
	qw422016.N().S(`<br></text_green></div>
    </div>
    <div id='block_info_footer' style='font-size: 20px;'> <a href='/project/`)
//line project.qtpl:26
	qw422016.N().D(project.ID)
//line project.qtpl:26
	qw422016.N().S(`'>read more</a></div>
    </div></div>
</article>
`)
//line project.qtpl:29
}

//line project.qtpl:29
func WriteFullProject(qq422016 qtio422016.Writer, project datastruct.Projects, tags map[int]datastruct.Tags, teamMembers map[int]datastruct.TeamMembers) {
//line project.qtpl:29
	qw422016 := qt422016.AcquireWriter(qq422016)
//line project.qtpl:29
	StreamFullProject(qw422016, project, tags, teamMembers)
//line project.qtpl:29
	qt422016.ReleaseWriter(qw422016)
//line project.qtpl:29
}

//line project.qtpl:29
func FullProject(project datastruct.Projects, tags map[int]datastruct.Tags, teamMembers map[int]datastruct.TeamMembers) string {
//line project.qtpl:29
	qb422016 := qt422016.AcquireByteBuffer()
//line project.qtpl:29
	WriteFullProject(qb422016, project, tags, teamMembers)
//line project.qtpl:29
	qs422016 := string(qb422016.B)
//line project.qtpl:29
	qt422016.ReleaseByteBuffer(qb422016)
//line project.qtpl:29
	return qs422016
//line project.qtpl:29
}
