// Code generated by qtc from "projects.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line projects.qtpl:1
package templates

//line projects.qtpl:1
import "tochkru-golang/internal/app/datastruct"

//line projects.qtpl:2
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line projects.qtpl:2
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line projects.qtpl:2
func StreamProjectsPage(qw422016 *qt422016.Writer, projects []datastruct.Projects, tags map[int]datastruct.Tags, teamMembers map[int]datastruct.TeamMembers, topTags []datastruct.Tags) {
//line projects.qtpl:2
	qw422016.N().S(`
`)
//line projects.qtpl:3
	qw422016.N().S(Header("Проекты"))
//line projects.qtpl:3
	qw422016.N().S(`
`)
//line projects.qtpl:4
	qw422016.N().S(Menu(topTags))
//line projects.qtpl:4
	qw422016.N().S(`
`)
//line projects.qtpl:5
	for i := 0; i < len(projects); i++ {
//line projects.qtpl:5
		qw422016.N().S(`
`)
//line projects.qtpl:6
		qw422016.N().S(Project(projects[i], tags, teamMembers))
//line projects.qtpl:6
		qw422016.N().S(`
`)
//line projects.qtpl:7
	}
//line projects.qtpl:7
	qw422016.N().S(`
`)
//line projects.qtpl:8
	qw422016.N().S(Footer())
//line projects.qtpl:8
	qw422016.N().S(`
`)
//line projects.qtpl:9
}

//line projects.qtpl:9
func WriteProjectsPage(qq422016 qtio422016.Writer, projects []datastruct.Projects, tags map[int]datastruct.Tags, teamMembers map[int]datastruct.TeamMembers, topTags []datastruct.Tags) {
//line projects.qtpl:9
	qw422016 := qt422016.AcquireWriter(qq422016)
//line projects.qtpl:9
	StreamProjectsPage(qw422016, projects, tags, teamMembers, topTags)
//line projects.qtpl:9
	qt422016.ReleaseWriter(qw422016)
//line projects.qtpl:9
}

//line projects.qtpl:9
func ProjectsPage(projects []datastruct.Projects, tags map[int]datastruct.Tags, teamMembers map[int]datastruct.TeamMembers, topTags []datastruct.Tags) string {
//line projects.qtpl:9
	qb422016 := qt422016.AcquireByteBuffer()
//line projects.qtpl:9
	WriteProjectsPage(qb422016, projects, tags, teamMembers, topTags)
//line projects.qtpl:9
	qs422016 := string(qb422016.B)
//line projects.qtpl:9
	qt422016.ReleaseByteBuffer(qb422016)
//line projects.qtpl:9
	return qs422016
//line projects.qtpl:9
}
