// Code generated by qtc from "team.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line team.qtpl:1
package templates

//line team.qtpl:1
import "tochkru-golang/internal/app/datastruct"

//line team.qtpl:2
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line team.qtpl:2
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line team.qtpl:2
func StreamTeamPage(qw422016 *qt422016.Writer, teamMembers []datastruct.TeamMembers, topTags []datastruct.Tags) {
//line team.qtpl:2
	qw422016.N().S(`
`)
//line team.qtpl:3
	qw422016.N().S(Header("Team"))
//line team.qtpl:3
	qw422016.N().S(`
`)
//line team.qtpl:4
	qw422016.N().S(Menu(topTags))
//line team.qtpl:4
	qw422016.N().S(`
<style>
table, th, td {
  border: 1px solid black;
  border-collapse: collapse;
}
</style>
<article id='block_news'>
<table width="30%">
    <tr>
        <th>ID</th>
        <th>Name</th>
    </tr>
    `)
//line team.qtpl:17
	for _, teamMember := range teamMembers {
//line team.qtpl:17
		qw422016.N().S(`
     <tr>
        <td>`)
//line team.qtpl:19
		qw422016.N().D(teamMember.ID)
//line team.qtpl:19
		qw422016.N().S(`</td>
        <td>`)
//line team.qtpl:20
		qw422016.E().S(teamMember.Name)
//line team.qtpl:20
		qw422016.N().S(`</td>
     </tr>
    `)
//line team.qtpl:22
	}
//line team.qtpl:22
	qw422016.N().S(`
</table>
</article>
`)
//line team.qtpl:25
	qw422016.N().S(Footer())
//line team.qtpl:25
	qw422016.N().S(`
`)
//line team.qtpl:26
}

//line team.qtpl:26
func WriteTeamPage(qq422016 qtio422016.Writer, teamMembers []datastruct.TeamMembers, topTags []datastruct.Tags) {
//line team.qtpl:26
	qw422016 := qt422016.AcquireWriter(qq422016)
//line team.qtpl:26
	StreamTeamPage(qw422016, teamMembers, topTags)
//line team.qtpl:26
	qt422016.ReleaseWriter(qw422016)
//line team.qtpl:26
}

//line team.qtpl:26
func TeamPage(teamMembers []datastruct.TeamMembers, topTags []datastruct.Tags) string {
//line team.qtpl:26
	qb422016 := qt422016.AcquireByteBuffer()
//line team.qtpl:26
	WriteTeamPage(qb422016, teamMembers, topTags)
//line team.qtpl:26
	qs422016 := string(qb422016.B)
//line team.qtpl:26
	qt422016.ReleaseByteBuffer(qb422016)
//line team.qtpl:26
	return qs422016
//line team.qtpl:26
}
