name: Build tochk.net

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Setup Go environment
        uses: actions/setup-go@v2.1.4
      - uses: actions/checkout@v2
      - name: Test
        run: make test
  build:
    runs-on: ubuntu-latest
    environment: prod
    steps:
    - name: Setup Go environment
      uses: actions/setup-go@v2.1.4
    - uses: actions/checkout@v2
    
    - name: Run generate
      run: make generate
    - name: Run build
      run: make build
  deploy:
    runs-on: ubuntu-latest
    environment: prod
    steps:
    - name: Deploy
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
        SOURCE: "bin/*"
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        TARGET: ${{ secrets.REMOTE_TARGET }}
