name: Makefile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Setup Go environment
      uses: actions/setup-go@v2.1.4
    
    - uses: actions/checkout@v2
    
    - name: Run generate
      run: make generate
      
    - name: Run build
      run: make build
