name: Build tochk.net

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
#  lint:
#    name: Run Linters
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/setup-go@v3
#        with:
#          go-version: 1.19
#      - uses: actions/checkout@v3
#      - name: Deps
#        run: go mod download
#      - name: golangci-lint
#        uses: golangci/golangci-lint-action@v3
#        with:
#          version: v1.29
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go environment
        uses: actions/setup-go@v2.1.4
        with:
          go-version: 1.19
      - uses: actions/checkout@v2
      - name: Test
        run: make test
  build-deploy:
    name: Build and deploy
    needs: [test]
    runs-on: ubuntu-latest
    environment: prod
    steps:
    - name: Setup Go environment
      uses: actions/setup-go@v3.5.0
      with:
        go-version: 1.19
    - uses: actions/checkout@v3.3.0
    
    - name: Run generate
      run: make generate
    - name: Run build
      run: make build-arm
    - name: Deploy
      uses: easingthemes/ssh-deploy@v4.0.5
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
        SOURCE: "bin/*"
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        TARGET: ${{ secrets.REMOTE_TARGET }}
    - name: Restart service
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: sudo systemctl restart tochknet
